apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi  # 存储容量（逻辑值，不影响本地目录大小）
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # 单节点读写
  persistentVolumeReclaimPolicy: Retain  # 删除 PVC 后保留数据
  storageClassName: local-storage
  local:
    path: /host/node/path  # 节点上的目录路径
  nodeAffinity:  # 绑定到特定节点
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: disk
          operator: In
          values:
          - ssd